package main

var apiAlive = `/***
	Author: Leong Kai Khee (Kurogami)
	Date: 2020

	Generated by DeviserGO
***/

package main

import (
	"net/http"
)

//Alive is an API to check if the server is in operation and functional
func Alive(w http.ResponseWriter, r *http.Request) {
	result := DeviserResponse{HTTPStatus: 200, Result: "OK"}
	result.DoResponse(w)
	return
}
`
