package main

/* PARSE IN VALUE
1. API Name (First char uppercase)
2. API Name (First char uppercase)
3. API Name (First char uppercase)
4. API Name (First char uppercase)
5. API Name (First char uppercase)
*/
var apiBase = `
/***
	Author: Leong Kai Khee (Kurogami)
	Date: 2020

	Generated by DeviserGO
***/

package main

import (
	"net/http"

	//"github.com/gorilla/mux"
)

//%sInput is the fields expected to be received
type %sInput struct {
	` + "Input string `json:\"inputNameInJson\"`" + `
}

//%sOutput is the fields expected to be sent
type %sOutput struct {
	` + "Output string `json:\"outputNameInJson\"`" + `
}

//%s is an API to ...
func %s(w http.ResponseWriter, r *http.Request) {
	result := DeviserResponse{HTTPStatus: 200, Result: %sOutput{Output:"OK"}}

	// 1.
	// Decode body into your input struct with
	// POST - json.NewDecoder(r.Body).Decode(&test)
	// GET - Param in request string - /articles?category=XXX&id=YYY
	// for key, value := range r.URL.Query() {}
	// GET - Param as part of path - /articles/{category}/{id:[0-9]+}
	// vars := mux.Vars(r)
	// category := vars["category"]

	// 2.
	// Update result.Result with your output struct
	result.DoResponse(w)
	return
}
`
