package main

/* PARSE IN VALUE
1. API Routes
1.1. API Name
1.2. API Name (First char uppercase)
1.3. API Method (To append middleware)
*/
var tpRouter = `/***
	Author: Leong Kai Khee (Kurogami)
	Date: 2020

	Generated by DeviserGO
***/

package main

import (
	"net/http"

	"github.com/gorilla/mux"
)

// SetRoutes is the main entry point for all API controllers
func SetRoutes(router *mux.Router) {
	router.HandleFunc("/alive", Alive).Methods("GET")
	%s
}
`
var tpRouterLogin = `
	router.HandleFunc("/login", Login).Methods("POST")`
var tpRouterLogout = `
	router.Handle("/logout", AuthMiddleware(http.HandlerFunc(Logout))).Methods("POST")`
var tpRouterPurgeToken = `
	router.HandleFunc("/purge", PurgeToken).Methods("POST")`
var tpRouterSimple = `
	router.HandleFunc("/%s", %s).Methods("%s")`
var tpRouterMiddleware = `
	router.Handle("/%s", %s).Methods("%s")`
var tpRouterAuth = `AuthMiddleware(%s)`
var tpRouterAcl = `ACLMiddleware(%s)`
var tpRouterAudit = `AuditMiddleware(%s)`
var tpRouterHandler = `http.HandlerFunc(%s)`
