package main

var tpSmtp = `/***
	Author: Leong Kai Khee (Kurogami)
	Date: 2020

	Generated by DeviserGO
***/

package main

import (
	"encoding/base64"
	"fmt"
	"net/smtp"
	"os"
	"strings"
)

// SendSMTPMail sends an email using the given receiver, subject and message
func SendSMTPMail(receiver []string, subject string, message string) error {
	smtpHost := os.Getenv("SMTP_HOST")
	smtpPort := os.Getenv("SMTP_PORT")
	smtpUser := os.Getenv("SMTP_USER")
	smtpPW := os.Getenv("SMTP_PW")

	// Authentication.
	auth := smtp.PlainAuth("", smtpUser, smtpPW, smtpHost)

	header := map[string]string{}
	header["From"] = smtpUser
	header["To"] = strings.Join(receiver[:], ";")
	header["Subject"] = subject
	header["MIME-Version"] = "1.0"
	header["Content-Type"] = "text/plain; charset=\"utf-8\""
	header["Content-Transfer-Encoding"] = "base64"

	content := ""
	for k, v := range header {
		content += fmt.Sprintf("%s: %s\r\n", k, v)
	}
	content += "\r\n" + base64.StdEncoding.EncodeToString([]byte(message))

	// Sending email.
	err := smtp.SendMail(smtpHost+":"+smtpPort, auth, smtpUser, receiver, []byte(content))
	if err != nil {
		LogError("[smtp.go] Error sending email to [" + strings.Join(receiver[:], ";") + "]")
		return err
	}

	return nil
}
`
